name: Publish to crates.io
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: codeberg-small-lazy
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "$CARGO_REGISTRY_TOKEN" | cargo login
          cargo publish
